### ISSUE TITLE
1.17 update [BUG]

### ISSUE THREAD

**Issue by comonier** [Errored-Innovations/HeadsPlus#44]
i do not test it ingame just reporting console warns:

[20:15:21] [Craft Scheduler Thread - 1/ERROR]: [HeadsPlus] Error thrown when creating the head for GLOW_SQUID. If it's a custom head, please double check the name. (Error code: 6)
[20:15:21] [Craft Scheduler Thread - 1/ERROR]: [HeadsPlus] Error thrown when creating the head for GOAT. If it's a custom head, please double check the name. (Error code: 6)

while its starting

**Comment by Thatsmusic99** [comment]
Expected behaviour at this time (unless you are on 1.17, PLEASE don't delete the bug template, it is there for a reason), it has no effect on the actual plugin, it is purely there for if the plugin is failing to add heads and someone misconfigures it. However, am expecting it to fix itself in PR #43.

**Comment by comonier** [comment]
i am on 1.17

**Comment by Thatsmusic99** [comment]
In which case, please reopen the issue with the actual template filled in, I have absolutely nothing to work with here because I don't know what HeadsPlus version you're on, what version of software you're on (and not just 1.17) or how the issue can be reproduced. Word in advance as well, please include your mobs.yml and customheads.yml files in the issue.

**Comment by Thatsmusic99** [comment]
Just found there's something I forgot to update when I added 1.17 support. The build for this will be available at https://ci.pluginwiki.us/job/HeadsPlus/30/ when built (if it gives a 404 or similar, you may have to wait) but not instantly released. Original point still stands though, for any issue report you open for any applicable plugin, please do follow the issue template, it's there for a reason and greatly helps us in fixing issues easier.
